version: '3.8'

services:
  mysql_app:
    image: mysql:8.0
    container_name: mysql_app
    restart: unless-stopped
    env_file:
      - ./setup/.env  # Load environment variables
    environment:
      MYSQL_ROOT_PASSWORD: ${APP_DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${APP_DB_NAME}
      MYSQL_USER: ${APP_DB_USER}
      MYSQL_PASSWORD: ${APP_DB_PASSWORD}
    ports:
      - "3308:3306"
    volumes:
      - mysql_app_data:/var/lib/mysql
      - ./setup/springdb.sql:/docker-entrypoint-initdb.d/springdb.sql
    networks:
      - app-network

  backend:
    build: ./backend/demo
    container_name: spring_backend
    restart: unless-stopped
    depends_on:
      - mysql_app
    env_file:
      - ./setup/.env  # Load environment variables
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql_app:3306/${APP_DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${APP_DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${APP_DB_PASSWORD}
    ports:
      - "9090:9090"
    profiles:
      - backend
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: vue_frontend
    restart: unless-stopped
    depends_on:
      - backend
    env_file:
      - ./setup/.env  # Load environment variables
    ports:
      - "7070:80"
    profiles:
      - frontend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql_app_data:
