version: '3.8'

services:
  mysql_keycloak:
    image: mysql:8.0
    container_name: mysql_keycloak
    restart: unless-stopped
    env_file:
      - ./setup/.env  # Load environment variables
    environment:
      MYSQL_ROOT_PASSWORD: ${KEYCLOAK_DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${KEYCLOAK_DB_NAME}
      MYSQL_USER: ${KEYCLOAK_DB_USER}
      MYSQL_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - mysql_keycloak_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
    networks:
      - app-network

  mysql_app:
    image: mysql:8.0
    container_name: mysql_app
    restart: unless-stopped
    env_file:
      - ./setup/.env  # Load environment variables
    environment:
      MYSQL_ROOT_PASSWORD: ${APP_DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${APP_DB_NAME}
      MYSQL_USER: ${APP_DB_USER}
      MYSQL_PASSWORD: ${APP_DB_PASSWORD}
    ports:
      - "3308:3306"
    volumes:
      - mysql_app_data:/var/lib/mysql
      - ./setup/springdb.sql:/docker-entrypoint-initdb.d/springdb.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
    networks:
      - app-network

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    restart: unless-stopped
    command: start-dev --import-realm
    env_file:
      - ./setup/.env  # Load environment variables
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_DB: mysql
      KC_DB_URL: jdbc:mysql://mysql_keycloak:3306/${KEYCLOAK_DB_NAME}
      KC_DB_USERNAME: ${KEYCLOAK_DB_USER}
      KC_DB_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
    volumes:
      - ./setup/SpringBootRealm-realm.json:/opt/keycloak/data/import/realm.json
    ports:
      - "8080:8080"
    depends_on:
      mysql_keycloak:
        condition: service_healthy
    networks:
      - app-network

  backend:
    build: ./backend/demo
    container_name: spring_backend
    restart: unless-stopped
    depends_on:
      mysql_app:
        condition: service_healthy
      keycloak:
        condition: service_healthy
    env_file:
      - ./setup/.env  # Load environment variables
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql_app:3306/${APP_DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${APP_DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${APP_DB_PASSWORD}
      KEYCLOAK_URL: http://keycloak:8080
    ports:
      - "9090:9090"
    profiles:
      - backend
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: vue_frontend
    restart: unless-stopped
    depends_on:
      - backend
    env_file:
      - ./setup/.env  # Load environment variables
    ports:
      - "7070:80"
    profiles:
      - frontend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql_keycloak_data:
  mysql_app_data:
