# Use Maven official image to build the project
FROM maven:3.9.6-eclipse-temurin-21 AS build

# Set the working directory inside the container
WORKDIR /app

# Copy only pom.xml first (for dependency caching)
COPY pom.xml ./
RUN mvn dependency:go-offline

# Copy the entire project
COPY . .

# Overwrite application.properties with the new one before building
COPY ../setup/application-docker.properties src/main/resources/application.properties

# Build the application
RUN mvn clean package -DskipTests

# Use OpenJDK as the runtime image
FROM openjdk:21-jdk-slim

# Set the working directory
WORKDIR /app

# Copy the built JAR file from the build stage
COPY --from=build /app/target/*.jar app.jar

# Expose the application's port
EXPOSE 9090

# Run the application
ENTRYPOINT ["java", "-jar", "app.jar"]
