# Use Maven official image to build the project 
FROM maven:3.9.6-eclipse-temurin-21 AS build

# Set the working directory inside the container
WORKDIR /app/demo

# Copy the project files
COPY . .

# Copy the .properties file from /env to the backend's resources folder
# COPY setup/application.properties /app/demo/src/main/resources/application.properties

# List files before running Maven to check if pom.xml exists
RUN ls -R /app/demo

# Set the working directory inside the container
WORKDIR /app/demo

# Build the application
RUN mvn clean package -DskipTests

# Use OpenJDK as the runtime image
FROM openjdk:21-jdk-slim

# Set the working directory
WORKDIR /app

# Copy the built JAR file from the build stage
COPY --from=build /app/demo/target/*.jar app.jar

# Expose the application's port
EXPOSE 9090

# Run the application
ENTRYPOINT ["java", "-jar", "app.jar"]
