apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared
spec:
  selector:
    matchLabels:
      app: cloudflared
  template:
    metadata:
      labels:
        app: cloudflared
    spec:
      dnsPolicy: "None"  # Use "None" to allow custom DNS configuration
      dnsConfig:
        nameservers:
          - "1.1.1.1"  # Cloudflare DNS
          - "8.8.8.8"  # Google DNS
        searches:
          - "default.svc.cluster.local"  # Optional, for internal Kubernetes DNS search
      containers:
        - name: cloudflared
          image: cloudflare/cloudflared:latest
          args:
            - tunnel
            - run
            - --token
            - "$(TUNNEL_TOKEN)"
          env:
            - name: TUNNEL_TOKEN
              valueFrom:
                secretKeyRef:
                  name: cloudflared-token
                  key: tunnel-token
          resources:
            limits:
              cpu: "100m"
